In [ ]:
#kukadiya janki n
#216270307088
#Practical:10 Write a Pandas program to implement following operation
#to find and drop the missing values from the given dataset


import pandas as pd

data = {'A': [1, 2, None, 4, 5],
        'B': [None, 2, 3, 4, None],
        'C': [1, 2, 3, 4, 5]}

df = pd.DataFrame(data)
print("Original DataFrame:")
print(df)

df_cleaned = df.dropna()
print("\nDataFrame after dropping missing values:")
print(df_cleaned)

In [ ]:
#kukadiya janki n
#216270307088
#Practical:10 Write a Pandas program to implement following operation
#to remove the duplicates from the given dataset.


import pandas as pd


data = {'A': [1, 2, 2, 3, 4, 4],
        'B': ['apple', 'banana', 'banana', 'cherry', 'date', 'date']}

df = pd.DataFrame(data)


print("Original DataFrame:")
print(df)


df_no_duplicates = df.drop_duplicates()

# Display the DataFrame after removing duplicates
print("\nDataFrame after removing duplicates:")
print(df_no_duplicates)